baseURL = "https://jav-car-1971.github.io/DataBase01/"
languageCode = "es"
title = "Documentación de Proyecto"
theme = "coder"
defaultContentLanguage = "es"
enableRobotsTXT = true
paginate = 5 # He añadido esto para que la lista de posts se pagine si tienes muchos

[params]
    author = "JavCar1971"
    info = "ninguna"
    description = "Es lo que hay"
    colorscheme = "auto"

[languages]
  [languages.es]
    weight = 1
    languageName = "Español"
    contentDir = "content/es"
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Blog"
        url = "/posts/"  # <-- CORREGIDO
        weight = 1
      [[languages.es.menu.main]]
        name = "Proyecto"
        url = "/about/"  # <-- CORREGIDO
        weight = 2
  
 # [languages.en] # Comentada para inhabilitar multilenguaje
 #   weight = 2 # Comentada para inhabilitar multilenguaje
 #   languageName = "English" # Comentada para inhabilitar multilenguaje
 #   contentDir = "content/en" # Comentada para inhabilitar multilenguaje
  
 # [languages.fr] # Comentada para inhabilitar multilenguaje
 #   weight = 3 # Comentada para inhabilitar multilenguaje
 #  languageName = "Français" # Comentada para inhabilitar multilenguaje 
 #  contentDir = "content/fr" # Comentada para inhabilitar multilenguaje
  
 # [languages.pt] # Comentada para inhabilitar multilenguaje
 #  weight = 4 # Comentada para inhabilitar multilenguaje
 #  languageName = "Português" # Comentada para inhabilitar multilenguaje
 #  contentDir = "content/pt" # Comentada para inhabilitar multilenguaje
